version: '3.8'

services:
  app:
    build:
      context: .
    restart: always
    environment:
      - APP_PORT=${APP_PORT}
    ports: 
      - ${APP_PORT}:5000
    networks:
      - backend
networks:
  backend:
    external: true